[wxhaskell-from-cvs @ 2003-07-21 19:29:38 by dleijen]
Improved mac install scripts

darcs-hash:20030721192938-deb31-57fa372691cc5488861db01f433304240614b8d3.gz

diff --git a/bin/wxhaskell-register b/bin/wxhaskell-register
--- a/bin/wxhaskell-register
+++ b/bin/wxhaskell-register
@@ -1,13 +1,49 @@
 #!/bin/sh
+
+# default installation directory is the current directory.
 installdir="`pwd`"
-arg="`echo \"$1\" | sed -e 's|[-_a-zA-Z0-9]*=||'`"
-case $1 in
-  -installdir=*|--installdir=*)
-     installdir="$arg";;
-  -?|--help|*)
-     echo "usage:"
-     echo "  wxhaskell-register  [--installdir=<dir>]"
-     exit 1;;
-esac
+
+# parse command-line arguments
+while : ; do
+  # put optional argument in the $arg variable
+  case "$1" in
+   -*=*) arg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
+   *)    arg= ;;
+  esac
+
+  # match on the arguments
+  case "$1" in
+    "") break;;	
+    -installdir=*|--installdir=*)
+       installdir="$arg";;
+    -?|--help)
+       echo "usage:"
+       echo "  wxhaskell-register  [--installdir=<dir>]"
+       exit 1;;
+    *) echo "error:" 1>&2
+       echo "  Unknown option \"$1\"." 1>&2
+       echo "" 1>&2
+       echo "usage:" 1>&2
+       echo "  wxhaskell-register  [--installdir=<dir>]" 1>&2
+       echo "" 1>&2
+       exit 2;;
+  esac
+  shift
+done
+
+
+# test if package files are found.
+if test ! -e "${installdir}/wxh.pkg"; then
+  echo "error: " 1>&2
+  echo "  Unable to find: ${installdir}/wxh.pkg" 1>&2
+  echo "  Please run this program from the wxHaskell installation directory" 1>&2
+  echo "  or specify the installation directory on the command line." 1>&2
+  echo "" 1>&2
+  echo "usage:" 1>&2
+  echo "  wxhaskell-register  [--installdir=<dir>]" 1>&2
+  exit 2
+fi
+
+# register the packages.
 env installdir=${installdir} ghc-pkg -u -i ${installdir}/wxh.pkg
 env installdir=${installdir} ghc-pkg -u -i ${installdir}/wx.pkg
